### PR TITLE
Update .markdownlint.yml

### PR DESCRIPTION
**Pull request by sigrunixia**
This is a mostly filled out rules Markdown linter that then allows us to toggle the options of it as we want.

I figure that would be easier than trying to slowly add in rule by rule. For those who have yet to use this, I suggest seeing how it affects your individual files to lint with some of these rules. 

Signed-off-by: Sigrunixia <Scholarlysigrun@icloud.com>

### CODE REVIEW

**Review by mProjectsCode — COMMENTED** [review]
This seems good to me, but before this PR is merged, it would be nice to see the linter in action. By that, I mean seeing how a file linted with this config looks.

**Comment by sigrunixia** [comment]
Today ended up being.. later. Stuff always comes up. :)

So running a lint on the fork on my side yeah there is some rules we definitely want to disable. Too much spam on that front. 

Let me showcase some examples of how it changes when a file follows linting parameters. 

Currently, it's running on defaults, and checking YML and other things, but I'll focus on markdown. This is the default setting for markdown in the linter action.

```yaml
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 400            # Line length 80 is far to short
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines
```

Now the file that is not here in the repo yet, Matcha-Latcha-Recipe.md received the following errors:
```
/github/workspace/Homebrew/Lore/Articles/Matcha-Latcha-Recipe.md:11:401 MD013/line-length Line length [Expected: 400; Actual: 633]
/github/workspace/Homebrew/Lore/Articles/Matcha-Latcha-Recipe.md:13 MD028/no-blanks-blockquote Blank line inside blockquote
/github/workspace/Homebrew/Lore/Articles/Matcha-Latcha-Recipe.md:16 MD045/no-alt-text Images should have alternate text (alt text)
/github/workspace/Homebrew/Lore/Articles/Matcha-Latcha-Recipe.md:52:401 MD013/line-length Line length [Expected: 400; Actual: 473]
```
image

image

Line 11: Chances are we might disable or greatly increase MD013. I'll show in a moment what the image look likes with us adhering to the 400 character limit. 

Line 13: MD028, I am voting to disable. With callouts, we are going to get too many false positives. 

Line 16: My bad, I SHOULD have alt text here for accessibility reasons. Come to think of it though, how does wikilcnks add accessibility alt-text?

Line 52 is the same with the text so it does not need to be shown again. 

A fixed MD013 and MD045 in this instance looks like this.

image
image

Note that alt text may not show on all Obsidian themes, but will show up on uploaded files. We can see that I had to change some of the wording of the callout, and it doesn't look quite right or natural. I'd probably bump it up further. Loren Epsom generators give me between 800-950 characters when I ask for 1 paragraph, so that would be what I propose MD013 be. 

Mainly, we just dont want to end up with these monsters of unreadable mess. Which on big PR's can be missed.

```
> [!abstract] Moo
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Ac turpis egestas sed tempus urna et pharetra. Augue mauris augue neque gravida. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Dignissim convallis aenean et tortor at risus. Sapien pellentesque habitant morbi tristique senectus et netus et malesuada. Nibh sit amet commodo nulla facilisi nullam vehicula. Vulputate odio ut enim blandit. Sit amet porttitor eget dolor morbi non arcu risus quis. Sapien eget mi proin sed libero enim sed faucibus turpis. Nibh praesent tristique magna sit amet. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Ut eu sem integer vitae justo. Quis varius quam quisque id diam vel. Ultrices in iaculis nunc sed augue lacus. Leo urna molestie at elementum eu facilisis. Malesuada fames ac turpis egestas integer eget aliquet nibh.Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Dolor sed viverra ipsum nunc aliquet bibendum. Leo a diam sollicitudin tempor id eu nisl nunc. Justo nec ultrices dui sapien. In ante metus dictum at tempor commodo ullamcorper a. Purus ut faucibus pulvinar elementum integer enim neque volutpat. Duis convallis convallis tellus id interdum velit laoreet id. Mattis vulputate enim nulla aliquet porttitor lacus luctus. At volutpat diam ut venenatis tellus in metus vulputate eu. Elementum integer enim neque volutpat ac tincidunt. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Egestas maecenas pharetra convallis posuere morbi leo urna. Amet cursus sit amet dictum sit amet justo donec enim.Id porta nibh venenatis cras sed felis eget. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Justo eget magna fermentum iaculis eu. Praesent tristique magna sit amet purus. Volutpat ac tincidunt vitae semper quis. Quis auctor elit sed vulputate mi sit amet. Porttitor leo a diam sollicitudin. Egestas integer eget aliquet nibh praesent tristique magna. Ultrices eros in cursus turpis massa tincidunt dui ut. Enim diam vulputate ut pharetra sit amet aliquam id diam. Nam libero justo laoreet sit amet cursus sit amet dictum. Enim nec dui nunc mattis enim ut tellus elementum. Quam pellentesque nec nam aliquam sem. Tristique magna sit amet purus. Vitae purus faucibus ornare suspendisse sed nisi lacus sed. Vitae tortor condimentum lacinia quis vel eros. Mi bibendum neque egestas congue quisque. Quis imperdiet massa tincidunt nunc pulvinar sapien.
```

image


I'll comment some more on other common ones I got.

**Comment by sigrunixia** [comment]
MD003/heading-style/header-style Heading style [Expected: atx; Actual: atx_closed]

What it sees:
```
# 
## 
### 
```

What it wants to see instead

```
# I 
## Am
### Header!
```

Worth Keeping this one I think. It's just a simple "Hey, you forgot your head..er!"

MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 1]
MD010/no-hard-tabs Hard tabs [Column: 1]

We have two conflicting rules here, somewhat. Number 10 does not like my hard tabs. So that would be an absolute no-no. I'd have to use spaces here if we kept number 10. Considering so many code forms like YAML are against hard tabs, we likely cannot get rid of it. 

For MD07.
What it sees. 
```md
Summon and drive your personal Mech/Vehicle, **Iron Bear**, for **2** turns.
- While driving it:
    - On your turn you can attack with each of its mounted weapons and perform a *Slam* attack.
```

What it wants:
```
Summon and drive your personal Mech/Vehicle, **Iron Bear**, for **2** turns.
- While driving it:
    - On your turn you can attack with each of its mounted weapons and perform a *Slam* attack.
```

**Comment by sigrunixia** [comment]
> This seems good to me, but before this PR is merged, it would be nice to see the linter in action. By that, I mean seeing how a file linted with this config looks.

Added a bunch of my comments into the file. To try to indicate how it may change things slightly.

Honestly, most of it is to keep things from mucking up with code blocks. o.o

**Pull request merged**
